 nome: CI-CD 

 on:
  empurrar:
    ramos: [ dev-b ]

jobs:
        
  construir:
    nome: Construir 
    em funcionamento: ubuntu-mais recente
    passos:
        - executado: echo CONSTRUINDO O SOFTWARE NO AMBIENTE DE DEV
      
  implantação-dev:
    nome: Teste em DEV
    necessidades: [construir]
    em funcionamento: ubuntu-mais recente
    passos:
      - usos: ações/checkout@v2
      - nome: Node de configuração.js
        usos: ações/node@v1 de configuração
        com:
          versão de nó: "14"

      # Instalar deps necessários para ação - brincadeira, jest-html-report
      - nome: Instalar dependências
        executar: npm instalar --save-dev brincadeira jest-html-reporter 

      # Finalmente, execute nossos testes
      - nome: Executar os testes
        execução: teste npm
        
      - nome: Gerar relatório
        execução: teste npm
      - nome: Relatório de upload
        usos: ações/upload-artifact@v2
        com:
          nome: jest-report
          caminho: './relatório de teste.html'
      - executado: echo REALIZANDO TESTES UNITARIOS
      
  teste-qa:
    nome: Mover código para QA e Testar
    necessidades: [implantação-dev]
    em funcionamento: ubuntu-mais recente
    passos:
      - executado: echo MOVENDO E TESTES DE INTEGRACAO EM AMBIENTE QA
        
  estágio de implantação:
    nome: Mover para STAGE
    necessidades: [testing-qa]
    em funcionamento: ubuntu-mais recente
    passos:
      - executado: echo MOVENDO PARA AMBIENTE DE PRE-PRODUCAO
      
  implantação-produção:
    nome: Lançar software em Produção
    necessidades: [estágio de implantação]
    em funcionamento: ubuntu-mais recente
    passos:
      - executado: echo LANCAMENTO DO SOFTWARE
